"""core ledger + audit trail

Revision ID: 0001
Revises: 0000
Create Date: 2026-07-08 15:27:15.896949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = '0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_trail',
    sa.Column('trail_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('record_id', sa.String(length=60), nullable=False),
    sa.Column('action', sa.Enum('insert', 'update', 'delete', name='audit_action', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('old_values', sa.Text(), nullable=True),
    sa.Column('new_values', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(length=60), nullable=False),
    sa.Column('timestamp', sa.String(length=40), nullable=False),
    sa.Column('previous_entry_hash', sa.String(length=64), nullable=False),
    sa.Column('entry_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('trail_id', name=op.f('pk_audit_trail'))
    )
    op.create_table('forward_pricing_rate_agreements',
    sa.Column('fpra_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_start', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_end', sa.Integer(), nullable=False),
    sa.Column('negotiated_date', sa.Date(), nullable=True),
    sa.Column('aco_name', sa.String(length=120), nullable=True),
    sa.Column('rates_covered', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'negotiated', 'expired', 'superseded', name='fpra_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('fpra_id', name=op.f('pk_forward_pricing_rate_agreements'))
    )
    op.create_table('periods',
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='period_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('reconciliation_status', sa.Enum('pending', 'passed', 'failed', name='reconciliation_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('period_id', name=op.f('pk_periods')),
    sa.UniqueConstraint('fiscal_year', 'period_number', name='fiscal_year_period')
    )
    op.create_table('persons',
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=True),
    sa.Column('is_executive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('person_id', name=op.f('pk_persons'))
    )
    op.create_table('regulatory_thresholds',
    sa.Column('threshold_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=60), nullable=False),
    sa.Column('value', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('statute', 'proposed_rule', 'final_rule', 'class_deviation', name='threshold_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('source_citation', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('threshold_id', name=op.f('pk_regulatory_thresholds'))
    )
    op.create_table('unallowable_cost_categories',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('far_citation', sa.String(length=30), nullable=False),
    sa.Column('category_name', sa.String(length=120), nullable=False),
    sa.Column('trap_logic_description', sa.Text(), nullable=True),
    sa.Column('detection_method', sa.Enum('account_code', 'keyword_pattern', 'receipt_parsing', 'rate_lookup', name='detection_method', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_unallowable_cost_categories'))
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('agency_type', sa.Enum('dod', 'civilian', name='agency_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('award_date', sa.Date(), nullable=False),
    sa.Column('performance_start_date', sa.Date(), nullable=True),
    sa.Column('performance_end_date', sa.Date(), nullable=True),
    sa.Column('contract_value', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('tina_threshold_snapshot', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('tina_threshold_id', sa.Integer(), nullable=True),
    sa.Column('cas_trigger_threshold_snapshot', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('cas_trigger_threshold_id', sa.Integer(), nullable=True),
    sa.Column('cas_coverage_type', sa.Enum('none', 'modified', 'full', name='cas_coverage_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('disclosure_required', sa.Boolean(), nullable=False),
    sa.Column('contractor_size', sa.Enum('small', 'other_than_small', name='contractor_size', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('is_nontraditional_dc', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cas_trigger_threshold_id'], ['regulatory_thresholds.threshold_id'], name=op.f('fk_contracts_cas_trigger_threshold_id_regulatory_thresholds')),
    sa.ForeignKeyConstraint(['superseded_by'], ['contracts.contract_id'], name=op.f('fk_contracts_superseded_by_contracts')),
    sa.ForeignKeyConstraint(['tina_threshold_id'], ['regulatory_thresholds.threshold_id'], name=op.f('fk_contracts_tina_threshold_id_regulatory_thresholds')),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_contracts'))
    )
    op.create_table('indirect_pools',
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('pool_name', sa.Enum('fringe', 'overhead', 'ga', name='pool_name', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('rate_type', sa.Enum('provisional', 'actual_final', 'forward_pricing', name='rate_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'superseded', 'locked', name='pool_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('pool_balance', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('allocation_base_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('calculated_rate', govcon.db.types.SafeNumeric(precision=12, scale=4), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('fpra_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fpra_id'], ['forward_pricing_rate_agreements.fpra_id'], name=op.f('fk_indirect_pools_fpra_id_forward_pricing_rate_agreements')),
    sa.ForeignKeyConstraint(['superseded_by'], ['indirect_pools.pool_id'], name=op.f('fk_indirect_pools_superseded_by_indirect_pools')),
    sa.PrimaryKeyConstraint('pool_id', name=op.f('pk_indirect_pools'))
    )
    op.create_table('contract_actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('task_order', 'modification', 'other_negotiated_action', name='contract_action_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('proposed_value', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('tina_exception_adequate_price_competition', sa.Boolean(), nullable=True),
    sa.Column('tina_exception_commercial_product_service', sa.Boolean(), nullable=True),
    sa.Column('tina_exception_prices_set_by_law', sa.Boolean(), nullable=True),
    sa.Column('tina_exception_waiver_granted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_contract_actions_contract_id_contracts')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_contract_actions'))
    )
    op.create_table('gl_accounts',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=120), nullable=False),
    sa.Column('cost_type', sa.Enum('direct', 'indirect', 'unallowable', name='cost_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('pool_assignment', sa.Integer(), nullable=True),
    sa.Column('far_31_205_citation', sa.Integer(), nullable=True),
    sa.Column('gaap_treatment', sa.Text(), nullable=True),
    sa.Column('cas_treatment', sa.Text(), nullable=True),
    sa.CheckConstraint("NOT (cost_type != 'indirect' AND pool_assignment IS NOT NULL)", name=op.f('ck_gl_accounts_pool_only_if_indirect')),
    sa.CheckConstraint("NOT (cost_type = 'indirect' AND pool_assignment IS NULL)", name=op.f('ck_gl_accounts_indirect_requires_pool')),
    sa.ForeignKeyConstraint(['far_31_205_citation'], ['unallowable_cost_categories.category_id'], name=op.f('fk_gl_accounts_far_31_205_citation_unallowable_cost_categories')),
    sa.ForeignKeyConstraint(['pool_assignment'], ['indirect_pools.pool_id'], name=op.f('fk_gl_accounts_pool_assignment_indirect_pools')),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_gl_accounts')),
    sa.UniqueConstraint('account_code', name=op.f('uq_gl_accounts_account_code'))
    )
    op.create_table('gl_transactions',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('allowability_vector', sa.JSON(), nullable=True),
    sa.Column('source_document', sa.String(length=200), nullable=True),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['gl_accounts.account_id'], name=op.f('fk_gl_transactions_account_id_gl_accounts')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_gl_transactions_contract_id_contracts')),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_gl_transactions_period_id_periods')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], name=op.f('fk_gl_transactions_person_id_persons')),
    sa.ForeignKeyConstraint(['superseded_by'], ['gl_transactions.transaction_id'], name=op.f('fk_gl_transactions_superseded_by_gl_transactions')),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_gl_transactions'))
    )
    op.create_table('jcl_entries',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('clin_id', sa.String(length=20), nullable=False),
    sa.Column('task_order_id', sa.Integer(), nullable=True),
    sa.Column('wbs_id', sa.String(length=40), nullable=False),
    sa.Column('cost_element', sa.Enum('labor', 'material', 'travel', 'odc', 'subcontract', name='cost_element', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('quantity', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=True),
    sa.Column('units_completed', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=True),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_jcl_entries_contract_id_contracts')),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_jcl_entries_period_id_periods')),
    sa.ForeignKeyConstraint(['task_order_id'], ['contract_actions.action_id'], name=op.f('fk_jcl_entries_task_order_id_contract_actions')),
    sa.PrimaryKeyConstraint('entry_id', name=op.f('pk_jcl_entries')),
    sa.UniqueConstraint('contract_id', 'clin_id', 'task_order_id', 'wbs_id', 'cost_element', 'period_id', name='jcl_accumulation_key')
    )
    # ### end Alembic commands ###

    _create_enforcement_triggers()


# ---------------------------------------------------------------------------
# DB-level enforcement (architecture spec §0 "compliance at the edge").
# On Postgres the append-only rules would ALSO be REVOKE UPDATE, DELETE ...
# FROM app_role; the triggers below are the SQLite equivalent (SQLite has no
# grants) and would be ported as plpgsql triggers on a Postgres move.
# Every trigger has a friendlier ORM-layer twin in govcon/db/guards.py that
# fires first in normal use; these are the backstop for raw SQL.
# ---------------------------------------------------------------------------

APPEND_ONLY_TRIGGERS = [
    # gl_transactions: append-only (spec §0.1 — corrections are reversing
    # entries via superseded_by, never in-place edits)
    """
    CREATE TRIGGER trg_gl_transactions_no_update BEFORE UPDATE ON gl_transactions
    BEGIN SELECT RAISE(ABORT, 'gl_transactions is append-only; post a reversing entry'); END
    """,
    """
    CREATE TRIGGER trg_gl_transactions_no_delete BEFORE DELETE ON gl_transactions
    BEGIN SELECT RAISE(ABORT, 'gl_transactions is append-only; rows can never be deleted'); END
    """,
    # audit_trail: tamper-evident, append-only by construction
    """
    CREATE TRIGGER trg_audit_trail_no_update BEFORE UPDATE ON audit_trail
    BEGIN SELECT RAISE(ABORT, 'audit_trail is append-only'); END
    """,
    """
    CREATE TRIGGER trg_audit_trail_no_delete BEFORE DELETE ON audit_trail
    BEGIN SELECT RAISE(ABORT, 'audit_trail is append-only'); END
    """,
    # contracts: five frozen columns after insert (spec §0.1) — IS NOT is
    # NULL-safe. superseded_by/version stay updatable for the version flow.
    """
    CREATE TRIGGER trg_contracts_immutable_cols BEFORE UPDATE ON contracts
    FOR EACH ROW
    WHEN NEW.award_date IS NOT OLD.award_date
      OR NEW.tina_threshold_snapshot IS NOT OLD.tina_threshold_snapshot
      OR NEW.tina_threshold_id IS NOT OLD.tina_threshold_id
      OR NEW.cas_trigger_threshold_snapshot IS NOT OLD.cas_trigger_threshold_snapshot
      OR NEW.cas_trigger_threshold_id IS NOT OLD.cas_trigger_threshold_id
    BEGIN SELECT RAISE(ABORT, 'contract award/threshold fields are immutable after insert; create a new contract version'); END
    """,
    # closed-period gate (spec §11 item 1: "no transaction can post to a
    # closed period" — both ledgers)
    """
    CREATE TRIGGER trg_gl_transactions_open_period BEFORE INSERT ON gl_transactions
    FOR EACH ROW
    WHEN (SELECT status FROM periods WHERE period_id = NEW.period_id) != 'open'
    BEGIN SELECT RAISE(ABORT, 'cannot post to a closed period'); END
    """,
    """
    CREATE TRIGGER trg_jcl_entries_open_period BEFORE INSERT ON jcl_entries
    FOR EACH ROW
    WHEN (SELECT status FROM periods WHERE period_id = NEW.period_id) != 'open'
    BEGIN SELECT RAISE(ABORT, 'cannot post to a closed period'); END
    """,
    # SF 1408 criterion B at the edge: a transaction on a direct-cost
    # account must reference a contract (subquery CHECKs are not allowed,
    # hence a trigger).
    """
    CREATE TRIGGER trg_gl_transactions_direct_needs_contract BEFORE INSERT ON gl_transactions
    FOR EACH ROW
    WHEN NEW.contract_id IS NULL
      AND (SELECT cost_type FROM gl_accounts WHERE account_id = NEW.account_id) = 'direct'
    BEGIN SELECT RAISE(ABORT, 'a direct-cost transaction must reference a contract (SF 1408 criterion B)'); END
    """,
]


def _create_enforcement_triggers() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":  # pragma: no cover - covered on PG by 0017
        return  # plpgsql equivalents are created by migration 0017
    for ddl in APPEND_ONLY_TRIGGERS:
        op.execute(sa.text(ddl))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jcl_entries')
    op.drop_table('gl_transactions')
    op.drop_table('gl_accounts')
    op.drop_table('contract_actions')
    op.drop_table('indirect_pools')
    op.drop_table('contracts')
    op.drop_table('unallowable_cost_categories')
    op.drop_table('regulatory_thresholds')
    op.drop_table('persons')
    op.drop_table('periods')
    op.drop_table('forward_pricing_rate_agreements')
    op.drop_table('audit_trail')
    # ### end Alembic commands ###
