"""phase 3 cas consistency tables

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-08 16:20:01.192934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_accounting_practices',
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('practice_area', sa.String(length=120), nullable=False),
    sa.Column('disclosed_treatment', sa.Enum('direct', 'indirect', name='disclosed_treatment', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('account_code_prefix', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['superseded_by'], ['cost_accounting_practices.practice_id'], name=op.f('fk_cost_accounting_practices_superseded_by_cost_accounting_practices')),
    sa.PrimaryKeyConstraint('practice_id', name=op.f('pk_cost_accounting_practices'))
    )
    op.create_table('practice_change_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('practice_id', sa.Integer(), nullable=False),
    sa.Column('new_practice_id', sa.Integer(), nullable=False),
    sa.Column('detected_date', sa.Date(), nullable=False),
    sa.Column('cost_impact_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('flagged', 'under_review', 'resolved', name='change_event_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['new_practice_id'], ['cost_accounting_practices.practice_id'], name=op.f('fk_practice_change_events_new_practice_id_cost_accounting_practices')),
    sa.ForeignKeyConstraint(['practice_id'], ['cost_accounting_practices.practice_id'], name=op.f('fk_practice_change_events_practice_id_cost_accounting_practices')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_practice_change_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('practice_change_events')
    op.drop_table('cost_accounting_practices')
    # ### end Alembic commands ###
