"""phase 4 rate engine tables

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-08 16:24:37.846305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: Union[str, Sequence[str], None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_calculation_runs',
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('run_type', sa.Enum('pool_rate', 'burdened_cost', name='run_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('inputs_snapshot', sa.Text(), nullable=False),
    sa.Column('result_value', govcon.db.types.SafeNumeric(precision=18, scale=6), nullable=False),
    sa.Column('regulatory_threshold_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pool_id'], ['indirect_pools.pool_id'], name=op.f('fk_rate_calculation_runs_pool_id_indirect_pools')),
    sa.ForeignKeyConstraint(['regulatory_threshold_id'], ['regulatory_thresholds.threshold_id'], name=op.f('fk_rate_calculation_runs_regulatory_threshold_id_regulatory_thresholds')),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_rate_calculation_runs'))
    )
    op.create_table('rate_true_ups',
    sa.Column('true_up_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('provisional_rate_snapshot', govcon.db.types.SafeNumeric(precision=12, scale=4), nullable=False),
    sa.Column('final_rate_snapshot', govcon.db.types.SafeNumeric(precision=12, scale=4), nullable=False),
    sa.Column('delta_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_impact_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('calculated_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['pool_id'], ['indirect_pools.pool_id'], name=op.f('fk_rate_true_ups_pool_id_indirect_pools')),
    sa.PrimaryKeyConstraint('true_up_id', name=op.f('pk_rate_true_ups'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_true_ups')
    op.drop_table('rate_calculation_runs')
    # ### end Alembic commands ###
