"""phase 5 billing and schedule tables

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-08 16:57:19.758053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ice_schedules',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.Enum('A', 'B', 'C', 'E', 'G', 'H', 'I', 'L', 'N', 'O', name='schedule_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('generated_date', sa.Date(), nullable=False),
    sa.Column('reconciliation_status', sa.Enum('pending', 'passed', 'failed', name='reconciliation_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('signer_name', sa.String(length=120), nullable=True),
    sa.Column('signer_role', sa.Enum('cfo', 'vp', 'other', name='signer_role', native_enum=False, create_constraint=True, length=40), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('schedule_id', name=op.f('pk_ice_schedules'))
    )
    op.create_table('payroll_registers',
    sa.Column('register_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('total_gross_payroll', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('source_document', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_payroll_registers_period_id_periods')),
    sa.PrimaryKeyConstraint('register_id', name=op.f('pk_payroll_registers'))
    )
    op.create_table('vouchers',
    sa.Column('voucher_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('amount_billed', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('billing_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'paid', name='voucher_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_vouchers_contract_id_contracts')),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_vouchers_period_id_periods')),
    sa.PrimaryKeyConstraint('voucher_id', name=op.f('pk_vouchers'))
    )
    # ### end Alembic commands ###

    _create_period_close_triggers()


# ---------------------------------------------------------------------------
# Spec §11 / §0.1 periods comments, enforced at the DB layer (SQLite; the
# Postgres port would be plpgsql triggers). ORM-layer twin: the gated
# close_period() service in govcon/services/period_close.py.
# ---------------------------------------------------------------------------

PERIOD_TRIGGERS = [
    # A period cannot transition to closed while reconciliation has not
    # passed — the close is a gated workflow action, not a flag (§11 item 2).
    """
    CREATE TRIGGER trg_periods_close_requires_reconciliation BEFORE UPDATE ON periods
    FOR EACH ROW
    WHEN NEW.status = 'closed' AND OLD.status != 'closed'
      AND NEW.reconciliation_status != 'passed'
    BEGIN SELECT RAISE(ABORT, 'period cannot close until the three-way reconciliation passes'); END
    """,
    # Once closed, status is not reversible — the explicit reopen procedure
    # is out of scope for v1 (§0.1 periods comment).
    """
    CREATE TRIGGER trg_periods_no_reopen BEFORE UPDATE ON periods
    FOR EACH ROW
    WHEN OLD.status = 'closed' AND NEW.status != 'closed'
    BEGIN SELECT RAISE(ABORT, 'a closed period cannot reopen (no v1 reopen procedure)'); END
    """,
]


def _create_period_close_triggers() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":  # pragma: no cover - SQLite-only for v1
        raise NotImplementedError("port period-close triggers to plpgsql first")
    for ddl in PERIOD_TRIGGERS:
        op.execute(sa.text(ddl))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text('DROP TRIGGER IF EXISTS trg_periods_close_requires_reconciliation'))
    op.execute(sa.text('DROP TRIGGER IF EXISTS trg_periods_no_reopen'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vouchers')
    op.drop_table('payroll_registers')
    op.drop_table('ice_schedules')
    # ### end Alembic commands ###
