"""phase 8 tina sweep tables

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-08 17:20:34.697221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tina_baselines',
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=True),
    sa.Column('baseline_date', sa.Date(), nullable=False),
    sa.Column('price_agreement_date', sa.Date(), nullable=False),
    sa.Column('sweep_status', sa.Enum('not_started', 'in_progress', 'complete', name='sweep_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('certification_status', sa.Enum('not_required', 'pending', 'certified', name='certification_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['contract_actions.action_id'], name=op.f('fk_tina_baselines_action_id_contract_actions')),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_tina_baselines_contract_id_contracts')),
    sa.PrimaryKeyConstraint('baseline_id', name=op.f('pk_tina_baselines'))
    )
    op.create_table('tina_baseline_assumptions',
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('assumption_type', sa.Enum('vendor_quote', 'labor_rate', 'indirect_rate', name='assumption_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('baseline_value', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('source_document', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['baseline_id'], ['tina_baselines.baseline_id'], name=op.f('fk_tina_baseline_assumptions_baseline_id_tina_baselines')),
    sa.PrimaryKeyConstraint('assumption_id', name=op.f('pk_tina_baseline_assumptions'))
    )
    op.create_table('tina_sweep_findings',
    sa.Column('finding_id', sa.Integer(), nullable=False),
    sa.Column('baseline_id', sa.Integer(), nullable=False),
    sa.Column('assumption_id', sa.Integer(), nullable=False),
    sa.Column('subsequent_transaction_id', sa.Integer(), nullable=True),
    sa.Column('subsequent_value', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('variance_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=True),
    sa.Column('materiality_threshold_used', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('match_method', sa.String(length=200), nullable=False),
    sa.Column('flagged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['tina_baseline_assumptions.assumption_id'], name=op.f('fk_tina_sweep_findings_assumption_id_tina_baseline_assumptions')),
    sa.ForeignKeyConstraint(['baseline_id'], ['tina_baselines.baseline_id'], name=op.f('fk_tina_sweep_findings_baseline_id_tina_baselines')),
    sa.ForeignKeyConstraint(['subsequent_transaction_id'], ['gl_transactions.transaction_id'], name=op.f('fk_tina_sweep_findings_subsequent_transaction_id_gl_transactions')),
    sa.PrimaryKeyConstraint('finding_id', name=op.f('pk_tina_sweep_findings'))
    )
    # ### end Alembic commands ###

    # §0.1: a TINA baseline is locked (immutable) once created — the dates
    # and contract/action linkage never change; only the workflow statuses do.
    if op.get_bind().dialect.name == "sqlite":  # plpgsql equivalent: migration 0017
        op.execute(sa.text("""
        CREATE TRIGGER trg_tina_baselines_locked BEFORE UPDATE ON tina_baselines
        FOR EACH ROW
        WHEN NEW.baseline_date IS NOT OLD.baseline_date
          OR NEW.price_agreement_date IS NOT OLD.price_agreement_date
          OR NEW.contract_id IS NOT OLD.contract_id
          OR NEW.action_id IS NOT OLD.action_id
        BEGIN SELECT RAISE(ABORT, 'tina baseline is locked once created'); END
        """))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text('DROP TRIGGER IF EXISTS trg_tina_baselines_locked'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tina_sweep_findings')
    op.drop_table('tina_baseline_assumptions')
    op.drop_table('tina_baselines')
    # ### end Alembic commands ###
