"""phase 9 rea cda eichleay tables

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-08 17:28:17.980719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eichleay_claims',
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('delay_start_date', sa.Date(), nullable=False),
    sa.Column('delay_end_date', sa.Date(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('government_caused_delay', sa.Boolean(), nullable=True),
    sa.Column('contractor_on_standby', sa.Boolean(), nullable=True),
    sa.Column('no_replacement_work', sa.Boolean(), nullable=True),
    sa.Column('contract_billings_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('total_company_billings_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('total_home_office_overhead', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_performance_days', sa.Integer(), nullable=False),
    sa.Column('allocable_overhead', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('daily_overhead_rate', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=False),
    sa.Column('unabsorbed_overhead_claim', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('status', sa.Enum('complete', 'incomplete', name='eichleay_claim_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_eichleay_claims_contract_id_contracts')),
    sa.PrimaryKeyConstraint('claim_id', name=op.f('pk_eichleay_claims'))
    )
    op.create_table('rea_cda_actions',
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('rea', 'cda_claim', name='rea_cda_action_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('cost_increase_total', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_decrease_total', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('certification_required', sa.Boolean(), nullable=True),
    sa.Column('certification_status', sa.Enum('not_required', 'pending', 'certified', name='rea_cda_certification_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('co_received_date', sa.Date(), nullable=True),
    sa.Column('co_response_deadline', sa.Date(), nullable=True),
    sa.Column('interest_accrual_start_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_rea_cda_actions_contract_id_contracts')),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_rea_cda_actions'))
    )
    op.create_table('rea_cda_line_items',
    sa.Column('line_item_id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('gl_transaction_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['rea_cda_actions.action_id'], name=op.f('fk_rea_cda_line_items_action_id_rea_cda_actions')),
    sa.ForeignKeyConstraint(['gl_transaction_id'], ['gl_transactions.transaction_id'], name=op.f('fk_rea_cda_line_items_gl_transaction_id_gl_transactions')),
    sa.PrimaryKeyConstraint('line_item_id', name=op.f('pk_rea_cda_line_items'))
    )
    # ### end Alembic commands ###

    # Seed the CDA claim certification threshold — a verified reg-ref §7
    # fact that previously had no regulatory_thresholds row (ground rule 2:
    # every threshold in application logic traces to a row). FROZEN here,
    # mirrored in govcon/seeds/regulatory_thresholds.py (drift-tested).
    thresholds = sa.table(
        "regulatory_thresholds",
        sa.column("rule_name", sa.String),
        sa.column("value", sa.Text),
        sa.column("effective_date", sa.Date),
        sa.column("superseded_date", sa.Date),
        sa.column("status", sa.String),
        sa.column("source_citation", sa.Text),
    )
    op.bulk_insert(thresholds, [dict(
        rule_name="CDA_CLAIM_CERT",
        value="100000.00",
        effective_date=None,
        superseded_date=None,
        status="statute",
        source_citation=(
            "FAR 33.207 / 41 U.S.C. 7103(f) per Reg-Ref §7: CDA claims over "
            "$100,000 require certification; CO decides within 60 days for "
            "claims at/below, or sets a firm date for larger claims"
        ),
    )])


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text("DELETE FROM regulatory_thresholds WHERE rule_name = 'CDA_CLAIM_CERT'"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rea_cda_line_items')
    op.drop_table('rea_cda_actions')
    op.drop_table('eichleay_claims')
    # ### end Alembic commands ###
