"""phase 11 monitoring and audit response tables

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-08 17:45:06.843956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('audit_type', sa.Enum('incurred_cost', 'forward_pricing', 'systems_cas_tina', 'claims_terminations', name='audit_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('response_deadline_days', sa.Integer(), nullable=False),
    sa.Column('computed_deadline_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('notification_received', 'document_collection', 'management_review', 'submitted', 'follow_up', 'closed', name='audit_notification_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('requested_documents', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=80), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_audit_notifications'))
    )
    op.create_table('audit_alert_log',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('alert_point', sa.Enum('t_30', 't_14', 't_7', 't_3', 't_1', name='alert_point', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('fired_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=80), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['audit_notifications.notification_id'], name=op.f('fk_audit_alert_log_notification_id_audit_notifications')),
    sa.PrimaryKeyConstraint('alert_id', name=op.f('pk_audit_alert_log'))
    )
    op.create_table('audit_response_tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('open', 'complete', 'overdue', name='audit_task_status', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['audit_notifications.notification_id'], name=op.f('fk_audit_response_tasks_notification_id_audit_notifications')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_audit_response_tasks'))
    )
    op.create_table('pbr_fluctuation_notes',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('variance_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('variance_pct', govcon.db.types.SafeNumeric(precision=12, scale=4), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.String(length=80), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_pbr_fluctuation_notes_period_id_periods')),
    sa.ForeignKeyConstraint(['pool_id'], ['indirect_pools.pool_id'], name=op.f('fk_pbr_fluctuation_notes_pool_id_indirect_pools')),
    sa.PrimaryKeyConstraint('note_id', name=op.f('pk_pbr_fluctuation_notes'))
    )
    # ### end Alembic commands ###

    # §13 / §0.1: the management-review sign-off gate at the DB layer —
    # status cannot advance to 'submitted' while reviewed_by/reviewed_at
    # are null. ORM twin: services/audit_response.advance_status().
    if op.get_bind().dialect.name == "sqlite":  # plpgsql equivalent: migration 0017
        op.execute(sa.text("""
        CREATE TRIGGER trg_audit_notifications_review_gate BEFORE UPDATE ON audit_notifications
        FOR EACH ROW
        WHEN NEW.status = 'submitted'
          AND (NEW.reviewed_by IS NULL OR NEW.reviewed_at IS NULL)
        BEGIN SELECT RAISE(ABORT, 'cannot submit without a management-review sign-off'); END
        """))


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(sa.text('DROP TRIGGER IF EXISTS trg_audit_notifications_review_gate'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pbr_fluctuation_notes')
    op.drop_table('audit_response_tasks')
    op.drop_table('audit_alert_log')
    op.drop_table('audit_notifications')
    # ### end Alembic commands ###
