"""phase 12 standard costing tables

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-08 17:50:32.430991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import govcon.db.types


# revision identifiers, used by Alembic.
revision: str = '0010'
down_revision: Union[str, Sequence[str], None] = '0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overhead_budgets',
    sa.Column('budget_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('fixed_overhead_budget', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('variable_overhead_rate', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_overhead_budgets_contract_id_contracts')),
    sa.PrimaryKeyConstraint('budget_id', name=op.f('pk_overhead_budgets'))
    )
    op.create_table('standard_costs',
    sa.Column('standard_cost_id', sa.Integer(), nullable=False),
    sa.Column('cost_element', sa.Enum('material', 'labor', 'overhead', name='standard_cost_element', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=True),
    sa.Column('operation_or_product_code', sa.String(length=40), nullable=False),
    sa.Column('standard_quantity', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=False),
    sa.Column('standard_rate', govcon.db.types.SafeNumeric(precision=18, scale=4), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.contract_id'], name=op.f('fk_standard_costs_contract_id_contracts')),
    sa.PrimaryKeyConstraint('standard_cost_id', name=op.f('pk_standard_costs'))
    )
    op.create_table('cost_variances',
    sa.Column('variance_id', sa.Integer(), nullable=False),
    sa.Column('standard_cost_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('jcl_entry_id', sa.Integer(), nullable=True),
    sa.Column('variance_type', sa.Enum('material_price', 'material_usage', 'labor_rate', 'labor_efficiency', 'overhead_volume', 'overhead_spending', name='variance_type', native_enum=False, create_constraint=True, length=40), nullable=False),
    sa.Column('standard_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('actual_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('variance_amount', govcon.db.types.SafeNumeric(precision=18, scale=2), nullable=False),
    sa.Column('favorable', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['jcl_entry_id'], ['jcl_entries.entry_id'], name=op.f('fk_cost_variances_jcl_entry_id_jcl_entries')),
    sa.ForeignKeyConstraint(['period_id'], ['periods.period_id'], name=op.f('fk_cost_variances_period_id_periods')),
    sa.ForeignKeyConstraint(['standard_cost_id'], ['standard_costs.standard_cost_id'], name=op.f('fk_cost_variances_standard_cost_id_standard_costs')),
    sa.PrimaryKeyConstraint('variance_id', name=op.f('pk_cost_variances'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_variances')
    op.drop_table('standard_costs')
    op.drop_table('overhead_budgets')
    # ### end Alembic commands ###
