"""v11 gl_accounts is_labor

Revision ID: 0011
Revises: 0010
Create Date: 2026-07-08 18:03:10.303734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


DIRECT_NEEDS_CONTRACT_TRIGGER = """
CREATE TRIGGER trg_gl_transactions_direct_needs_contract BEFORE INSERT ON gl_transactions
FOR EACH ROW
WHEN NEW.contract_id IS NULL
  AND (SELECT cost_type FROM gl_accounts WHERE account_id = NEW.account_id) = 'direct'
BEGIN SELECT RAISE(ABORT, 'a direct-cost transaction must reference a contract (SF 1408 criterion B)'); END
"""

def upgrade() -> None:
    """Upgrade schema."""
    # SQLite batch mode rebuilds gl_accounts (drop + rename); the Phase-1
    # trigger on gl_transactions references gl_accounts and blocks the
    # rename — drop it around the alter and recreate it verbatim after.
    # (SQLite-only dance; the plpgsql equivalent is created by 0017.)
    sqlite = op.get_bind().dialect.name == "sqlite"
    if sqlite:
        op.execute(sa.text("DROP TRIGGER IF EXISTS trg_gl_transactions_direct_needs_contract"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        # server_default so existing rows backfill to false (labor accounts
        # are then flagged deliberately, never assumed).
        batch_op.add_column(
            sa.Column('is_labor', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###
    if sqlite:
        op.execute(sa.text(DIRECT_NEEDS_CONTRACT_TRIGGER))


def downgrade() -> None:
    """Downgrade schema."""
    sqlite = op.get_bind().dialect.name == "sqlite"
    if sqlite:
        op.execute(sa.text("DROP TRIGGER IF EXISTS trg_gl_transactions_direct_needs_contract"))
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gl_accounts', schema=None) as batch_op:
        batch_op.drop_column('is_labor')

    # ### end Alembic commands ###
    if sqlite:
        op.execute(sa.text(DIRECT_NEEDS_CONTRACT_TRIGGER))
